"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import stubs.file_logger_service_pb2 as file_logger_service_pb2
import grpc
import grpc.aio
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class FileLoggerServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    InitializeFile: grpc.UnaryUnaryMultiCallable[
        file_logger_service_pb2.InitializeFileRequest,
        file_logger_service_pb2.InitializeFileResponse,
    ]

    LogData: grpc.UnaryUnaryMultiCallable[
        file_logger_service_pb2.LogDataRequest,
        file_logger_service_pb2.LogDataResponse,
    ]

    CloseFile: grpc.UnaryUnaryMultiCallable[
        file_logger_service_pb2.CloseFileRequest,
        file_logger_service_pb2.CloseFileResponse,
    ]

class FileLoggerServiceAsyncStub:
    InitializeFile: grpc.aio.UnaryUnaryMultiCallable[
        file_logger_service_pb2.InitializeFileRequest,
        file_logger_service_pb2.InitializeFileResponse,
    ]

    LogData: grpc.aio.UnaryUnaryMultiCallable[
        file_logger_service_pb2.LogDataRequest,
        file_logger_service_pb2.LogDataResponse,
    ]

    CloseFile: grpc.aio.UnaryUnaryMultiCallable[
        file_logger_service_pb2.CloseFileRequest,
        file_logger_service_pb2.CloseFileResponse,
    ]

class FileLoggerServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def InitializeFile(
        self,
        request: file_logger_service_pb2.InitializeFileRequest,
        context: _ServicerContext,
    ) -> typing.Union[file_logger_service_pb2.InitializeFileResponse, collections.abc.Awaitable[file_logger_service_pb2.InitializeFileResponse]]: ...

    @abc.abstractmethod
    def LogData(
        self,
        request: file_logger_service_pb2.LogDataRequest,
        context: _ServicerContext,
    ) -> typing.Union[file_logger_service_pb2.LogDataResponse, collections.abc.Awaitable[file_logger_service_pb2.LogDataResponse]]: ...

    @abc.abstractmethod
    def CloseFile(
        self,
        request: file_logger_service_pb2.CloseFileRequest,
        context: _ServicerContext,
    ) -> typing.Union[file_logger_service_pb2.CloseFileResponse, collections.abc.Awaitable[file_logger_service_pb2.CloseFileResponse]]: ...

def add_FileLoggerServiceServicer_to_server(servicer: FileLoggerServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
