# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_logger_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'file_logger_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x66ile_logger_service.proto\x12\x13\x66ile_logger_service\"\x7f\n\x15InitializeFileRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12S\n\x17initialization_behavior\x18\x02 \x01(\x0e\x32\x32.file_logger_service.SessionInitializationBehavior\"C\n\x16InitializeFileResponse\x12\x14\n\x0csession_name\x18\x01 \x01(\t\x12\x13\n\x0bnew_session\x18\x02 \x01(\x08\"7\n\x0eLogDataRequest\x12\x14\n\x0csession_name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\x11\n\x0fLogDataResponse\"(\n\x10\x43loseFileRequest\x12\x14\n\x0csession_name\x18\x01 \x01(\t\"\x13\n\x11\x43loseFileResponse*\xbc\x01\n\x1dSessionInitializationBehavior\x12/\n+SESSION_INITIALIZATION_BEHAVIOR_UNSPECIFIED\x10\x00\x12\x32\n.SESSION_INITIALIZATION_BEHAVIOR_INITIALIZE_NEW\x10\x01\x12\x36\n2SESSION_INITIALIZATION_BEHAVIOR_ATTACH_TO_EXISTING\x10\x02\x32\xb0\x02\n\x11\x46ileLoggerService\x12i\n\x0eInitializeFile\x12*.file_logger_service.InitializeFileRequest\x1a+.file_logger_service.InitializeFileResponse\x12T\n\x07LogData\x12#.file_logger_service.LogDataRequest\x1a$.file_logger_service.LogDataResponse\x12Z\n\tCloseFile\x12%.file_logger_service.CloseFileRequest\x1a&.file_logger_service.CloseFileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_logger_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SESSIONINITIALIZATIONBEHAVIOR']._serialized_start=388
  _globals['_SESSIONINITIALIZATIONBEHAVIOR']._serialized_end=576
  _globals['_INITIALIZEFILEREQUEST']._serialized_start=50
  _globals['_INITIALIZEFILEREQUEST']._serialized_end=177
  _globals['_INITIALIZEFILERESPONSE']._serialized_start=179
  _globals['_INITIALIZEFILERESPONSE']._serialized_end=246
  _globals['_LOGDATAREQUEST']._serialized_start=248
  _globals['_LOGDATAREQUEST']._serialized_end=303
  _globals['_LOGDATARESPONSE']._serialized_start=305
  _globals['_LOGDATARESPONSE']._serialized_end=322
  _globals['_CLOSEFILEREQUEST']._serialized_start=324
  _globals['_CLOSEFILEREQUEST']._serialized_end=364
  _globals['_CLOSEFILERESPONSE']._serialized_start=366
  _globals['_CLOSEFILERESPONSE']._serialized_end=385
  _globals['_FILELOGGERSERVICE']._serialized_start=579
  _globals['_FILELOGGERSERVICE']._serialized_end=883
# @@protoc_insertion_point(module_scope)
