"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _InitializationBehavior:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _InitializationBehaviorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_InitializationBehavior.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    AUTO: _InitializationBehavior.ValueType  # 0
    """Automatically decide whether to initialize or attach."""
    INITIALIZE_NEW: _InitializationBehavior.ValueType  # 1
    """Always create a new session."""
    ATTACH_TO_EXISTING: _InitializationBehavior.ValueType  # 2
    """Always attach to an existing session."""

class InitializationBehavior(_InitializationBehavior, metaclass=_InitializationBehaviorEnumTypeWrapper):
    """Enum to define initialization behavior."""

AUTO: InitializationBehavior.ValueType  # 0
"""Automatically decide whether to initialize or attach."""
INITIALIZE_NEW: InitializationBehavior.ValueType  # 1
"""Always create a new session."""
ATTACH_TO_EXISTING: InitializationBehavior.ValueType  # 2
"""Always attach to an existing session."""
global___InitializationBehavior = InitializationBehavior

@typing.final
class InitializeFileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FILE_NAME_FIELD_NUMBER: builtins.int
    INITIALIZATION_BEHAVIOR_FIELD_NUMBER: builtins.int
    file_name: builtins.str
    """Also the session name."""
    initialization_behavior: global___InitializationBehavior.ValueType
    """Defines how the session should be initialized."""
    def __init__(
        self,
        *,
        file_name: builtins.str = ...,
        initialization_behavior: global___InitializationBehavior.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["file_name", b"file_name", "initialization_behavior", b"initialization_behavior"]) -> None: ...

global___InitializeFileRequest = InitializeFileRequest

@typing.final
class InitializeFileResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FILE_NAME_FIELD_NUMBER: builtins.int
    NEW_SESSION_FIELD_NUMBER: builtins.int
    file_name: builtins.str
    new_session: builtins.bool
    def __init__(
        self,
        *,
        file_name: builtins.str = ...,
        new_session: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["file_name", b"file_name", "new_session", b"new_session"]) -> None: ...

global___InitializeFileResponse = InitializeFileResponse

@typing.final
class LogDataRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FILE_NAME_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    file_name: builtins.str
    content: builtins.str
    def __init__(
        self,
        *,
        file_name: builtins.str = ...,
        content: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["content", b"content", "file_name", b"file_name"]) -> None: ...

global___LogDataRequest = LogDataRequest

@typing.final
class LogDataResponse(google.protobuf.message.Message):
    """Empty response message; success is indicated by the gRPC status code."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___LogDataResponse = LogDataResponse

@typing.final
class CloseFileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FILE_NAME_FIELD_NUMBER: builtins.int
    file_name: builtins.str
    def __init__(
        self,
        *,
        file_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["file_name", b"file_name"]) -> None: ...

global___CloseFileRequest = CloseFileRequest

@typing.final
class CloseFileResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___CloseFileResponse = CloseFileResponse
