# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logger_service.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'logger_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14logger_service.proto\x12\x0elogger_service\"s\n\x15InitializeFileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12G\n\x17initialization_behavior\x18\x02 \x01(\x0e\x32&.logger_service.InitializationBehavior\"@\n\x16InitializeFileResponse\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x13\n\x0bnew_session\x18\x02 \x01(\x08\"4\n\x0eLogDataRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\x11\n\x0fLogDataResponse\"%\n\x10\x43loseFileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"\x13\n\x11\x43loseFileResponse*N\n\x16InitializationBehavior\x12\x08\n\x04\x41UTO\x10\x00\x12\x12\n\x0eINITIALIZE_NEW\x10\x01\x12\x16\n\x12\x41TTACH_TO_EXISTING\x10\x02\x32\x8f\x02\n\x0elogger_service\x12_\n\x0eInitializeFile\x12%.logger_service.InitializeFileRequest\x1a&.logger_service.InitializeFileResponse\x12J\n\x07LogData\x12\x1e.logger_service.LogDataRequest\x1a\x1f.logger_service.LogDataResponse\x12P\n\tCloseFile\x12 .logger_service.CloseFileRequest\x1a!.logger_service.CloseFileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logger_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INITIALIZATIONBEHAVIOR']._serialized_start=356
  _globals['_INITIALIZATIONBEHAVIOR']._serialized_end=434
  _globals['_INITIALIZEFILEREQUEST']._serialized_start=40
  _globals['_INITIALIZEFILEREQUEST']._serialized_end=155
  _globals['_INITIALIZEFILERESPONSE']._serialized_start=157
  _globals['_INITIALIZEFILERESPONSE']._serialized_end=221
  _globals['_LOGDATAREQUEST']._serialized_start=223
  _globals['_LOGDATAREQUEST']._serialized_end=275
  _globals['_LOGDATARESPONSE']._serialized_start=277
  _globals['_LOGDATARESPONSE']._serialized_end=294
  _globals['_CLOSEFILEREQUEST']._serialized_start=296
  _globals['_CLOSEFILEREQUEST']._serialized_end=333
  _globals['_CLOSEFILERESPONSE']._serialized_start=335
  _globals['_CLOSEFILERESPONSE']._serialized_end=354
  _globals['_LOGGER_SERVICE']._serialized_start=437
  _globals['_LOGGER_SERVICE']._serialized_end=708
# @@protoc_insertion_point(module_scope)
