"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _SessionInitializationBehavior:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SessionInitializationBehaviorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SessionInitializationBehavior.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SESSION_INITIALIZATION_BEHAVIOR_UNSPECIFIED: _SessionInitializationBehavior.ValueType  # 0
    """Automatically decide whether to initialize new or attach."""
    SESSION_INITIALIZATION_BEHAVIOR_INITIALIZE_NEW: _SessionInitializationBehavior.ValueType  # 1
    SESSION_INITIALIZATION_BEHAVIOR_ATTACH_TO_EXISTING: _SessionInitializationBehavior.ValueType  # 2

class SessionInitializationBehavior(_SessionInitializationBehavior, metaclass=_SessionInitializationBehaviorEnumTypeWrapper): ...

SESSION_INITIALIZATION_BEHAVIOR_UNSPECIFIED: SessionInitializationBehavior.ValueType  # 0
"""Automatically decide whether to initialize new or attach."""
SESSION_INITIALIZATION_BEHAVIOR_INITIALIZE_NEW: SessionInitializationBehavior.ValueType  # 1
SESSION_INITIALIZATION_BEHAVIOR_ATTACH_TO_EXISTING: SessionInitializationBehavior.ValueType  # 2
global___SessionInitializationBehavior = SessionInitializationBehavior

@typing.final
class InitializeFileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FILE_PATH_FIELD_NUMBER: builtins.int
    INITIALIZATION_BEHAVIOR_FIELD_NUMBER: builtins.int
    file_path: builtins.str
    """The complete file path."""
    initialization_behavior: global___SessionInitializationBehavior.ValueType
    """Defines how the session should be initialized."""
    def __init__(
        self,
        *,
        file_path: builtins.str = ...,
        initialization_behavior: global___SessionInitializationBehavior.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["file_path", b"file_path", "initialization_behavior", b"initialization_behavior"]) -> None: ...

global___InitializeFileRequest = InitializeFileRequest

@typing.final
class InitializeFileResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_NAME_FIELD_NUMBER: builtins.int
    NEW_SESSION_FIELD_NUMBER: builtins.int
    session_name: builtins.str
    new_session: builtins.bool
    def __init__(
        self,
        *,
        session_name: builtins.str = ...,
        new_session: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["new_session", b"new_session", "session_name", b"session_name"]) -> None: ...

global___InitializeFileResponse = InitializeFileResponse

@typing.final
class LogDataRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_NAME_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    session_name: builtins.str
    @property
    def data(self) -> global___Measurement: ...
    def __init__(
        self,
        *,
        session_name: builtins.str = ...,
        data: global___Measurement | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["data", b"data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "session_name", b"session_name"]) -> None: ...

global___LogDataRequest = LogDataRequest

@typing.final
class LogDataResponse(google.protobuf.message.Message):
    """Empty response message; success is indicated by the gRPC status code."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___LogDataResponse = LogDataResponse

@typing.final
class CloseFileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_NAME_FIELD_NUMBER: builtins.int
    session_name: builtins.str
    def __init__(
        self,
        *,
        session_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["session_name", b"session_name"]) -> None: ...

global___CloseFileRequest = CloseFileRequest

@typing.final
class CloseFileResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___CloseFileResponse = CloseFileResponse

@typing.final
class Measurement(google.protobuf.message.Message):
    """Represents the Measurement data to be logged."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MEASUREMENT_NAME_FIELD_NUMBER: builtins.int
    MEASUREMENT_CONFIGURATION_FIELD_NUMBER: builtins.int
    MEASUREMENT_OUTPUT_FIELD_NUMBER: builtins.int
    measurement_name: builtins.str
    measurement_configuration: builtins.str
    measurement_output: builtins.str
    def __init__(
        self,
        *,
        measurement_name: builtins.str = ...,
        measurement_configuration: builtins.str = ...,
        measurement_output: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["measurement_configuration", b"measurement_configuration", "measurement_name", b"measurement_name", "measurement_output", b"measurement_output"]) -> None: ...

global___Measurement = Measurement
