# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: json_logger.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'json_logger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11json_logger.proto\x12\x0bjson_logger\x1a\x1fgoogle/protobuf/timestamp.proto\"w\n\x15InitializeFileRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12K\n\x17initialization_behavior\x18\x02 \x01(\x0e\x32*.json_logger.SessionInitializationBehavior\"C\n\x16InitializeFileResponse\x12\x14\n\x0csession_name\x18\x01 \x01(\t\x12\x13\n\x0bnew_session\x18\x02 \x01(\x08\"\xbf\x03\n\x19LogMeasurementDataRequest\x12\x14\n\x0csession_name\x18\x01 \x01(\t\x12\x18\n\x10measurement_name\x18\x02 \x01(\t\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12i\n\x1ameasurement_configurations\x18\x04 \x03(\x0b\x32\x45.json_logger.LogMeasurementDataRequest.MeasurementConfigurationsEntry\x12[\n\x13measurement_outputs\x18\x05 \x03(\x0b\x32>.json_logger.LogMeasurementDataRequest.MeasurementOutputsEntry\x1a@\n\x1eMeasurementConfigurationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x39\n\x17MeasurementOutputsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1c\n\x1aLogMeasurementDataResponse\"(\n\x10\x43loseFileRequest\x12\x14\n\x0csession_name\x18\x01 \x01(\t\"\x13\n\x11\x43loseFileResponse*\xbc\x01\n\x1dSessionInitializationBehavior\x12/\n+SESSION_INITIALIZATION_BEHAVIOR_UNSPECIFIED\x10\x00\x12\x32\n.SESSION_INITIALIZATION_BEHAVIOR_INITIALIZE_NEW\x10\x01\x12\x36\n2SESSION_INITIALIZATION_BEHAVIOR_ATTACH_TO_EXISTING\x10\x02\x32\x9a\x02\n\nJsonLogger\x12Y\n\x0eInitializeFile\x12\".json_logger.InitializeFileRequest\x1a#.json_logger.InitializeFileResponse\x12\x65\n\x12LogMeasurementData\x12&.json_logger.LogMeasurementDataRequest\x1a\'.json_logger.LogMeasurementDataResponse\x12J\n\tCloseFile\x12\x1d.json_logger.CloseFileRequest\x1a\x1e.json_logger.CloseFileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'json_logger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGMEASUREMENTDATAREQUEST_MEASUREMENTCONFIGURATIONSENTRY']._loaded_options = None
  _globals['_LOGMEASUREMENTDATAREQUEST_MEASUREMENTCONFIGURATIONSENTRY']._serialized_options = b'8\001'
  _globals['_LOGMEASUREMENTDATAREQUEST_MEASUREMENTOUTPUTSENTRY']._loaded_options = None
  _globals['_LOGMEASUREMENTDATAREQUEST_MEASUREMENTOUTPUTSENTRY']._serialized_options = b'8\001'
  _globals['_SESSIONINITIALIZATIONBEHAVIOR']._serialized_start=801
  _globals['_SESSIONINITIALIZATIONBEHAVIOR']._serialized_end=989
  _globals['_INITIALIZEFILEREQUEST']._serialized_start=67
  _globals['_INITIALIZEFILEREQUEST']._serialized_end=186
  _globals['_INITIALIZEFILERESPONSE']._serialized_start=188
  _globals['_INITIALIZEFILERESPONSE']._serialized_end=255
  _globals['_LOGMEASUREMENTDATAREQUEST']._serialized_start=258
  _globals['_LOGMEASUREMENTDATAREQUEST']._serialized_end=705
  _globals['_LOGMEASUREMENTDATAREQUEST_MEASUREMENTCONFIGURATIONSENTRY']._serialized_start=582
  _globals['_LOGMEASUREMENTDATAREQUEST_MEASUREMENTCONFIGURATIONSENTRY']._serialized_end=646
  _globals['_LOGMEASUREMENTDATAREQUEST_MEASUREMENTOUTPUTSENTRY']._serialized_start=648
  _globals['_LOGMEASUREMENTDATAREQUEST_MEASUREMENTOUTPUTSENTRY']._serialized_end=705
  _globals['_LOGMEASUREMENTDATARESPONSE']._serialized_start=707
  _globals['_LOGMEASUREMENTDATARESPONSE']._serialized_end=735
  _globals['_CLOSEFILEREQUEST']._serialized_start=737
  _globals['_CLOSEFILEREQUEST']._serialized_end=777
  _globals['_CLOSEFILERESPONSE']._serialized_start=779
  _globals['_CLOSEFILERESPONSE']._serialized_end=798
  _globals['_JSONLOGGER']._serialized_start=992
  _globals['_JSONLOGGER']._serialized_end=1274
# @@protoc_insertion_point(module_scope)
