# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc
import logger_service_pb2 as logger__service__pb2

GRPC_GENERATED_VERSION = "1.71.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in logger_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class logger_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitializeFile = channel.unary_unary(
            "/logger_service.logger_service/InitializeFile",
            request_serializer=logger__service__pb2.InitializeFileRequest.SerializeToString,
            response_deserializer=logger__service__pb2.InitializeFileResponse.FromString,
            _registered_method=True,
        )
        self.LogData = channel.unary_unary(
            "/logger_service.logger_service/LogData",
            request_serializer=logger__service__pb2.LogDataRequest.SerializeToString,
            response_deserializer=logger__service__pb2.LogDataResponse.FromString,
            _registered_method=True,
        )
        self.CloseFile = channel.unary_unary(
            "/logger_service.logger_service/CloseFile",
            request_serializer=logger__service__pb2.CloseFileRequest.SerializeToString,
            response_deserializer=logger__service__pb2.CloseFileResponse.FromString,
            _registered_method=True,
        )


class logger_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitializeFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def LogData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CloseFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_logger_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "InitializeFile": grpc.unary_unary_rpc_method_handler(
            servicer.InitializeFile,
            request_deserializer=logger__service__pb2.InitializeFileRequest.FromString,
            response_serializer=logger__service__pb2.InitializeFileResponse.SerializeToString,
        ),
        "LogData": grpc.unary_unary_rpc_method_handler(
            servicer.LogData,
            request_deserializer=logger__service__pb2.LogDataRequest.FromString,
            response_serializer=logger__service__pb2.LogDataResponse.SerializeToString,
        ),
        "CloseFile": grpc.unary_unary_rpc_method_handler(
            servicer.CloseFile,
            request_deserializer=logger__service__pb2.CloseFileRequest.FromString,
            response_serializer=logger__service__pb2.CloseFileResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "logger_service.logger_service", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("logger_service.logger_service", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class logger_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitializeFile(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/logger_service.logger_service/InitializeFile",
            logger__service__pb2.InitializeFileRequest.SerializeToString,
            logger__service__pb2.InitializeFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def LogData(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/logger_service.logger_service/LogData",
            logger__service__pb2.LogDataRequest.SerializeToString,
            logger__service__pb2.LogDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CloseFile(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/logger_service.logger_service/CloseFile",
            logger__service__pb2.CloseFileRequest.SerializeToString,
            logger__service__pb2.CloseFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
