[tool.poetry]
name = "device_comm_proto_stubs"
version = "1.0.0"
description = "gRPC stubs for device communication service"
packages = [{ include = "device_comm_proto_stubs" }]

[tool.poetry.dependencies]
python = "^3.9"
grpcio-tools = ">=1.71.0,<2.0.0"
mypy-protobuf = ">=3.6.0,<4.0.0"