"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import file_logger_service.stubs.session_pb2 as session_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class InitializeFileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FILE_PATH_FIELD_NUMBER: builtins.int
    INITIALIZATION_BEHAVIOR_FIELD_NUMBER: builtins.int
    file_path: builtins.str
    """The complete file path."""
    initialization_behavior: session_pb2.SessionInitializationBehavior.ValueType
    """Defines how the session should be initialized."""
    def __init__(
        self,
        *,
        file_path: builtins.str = ...,
        initialization_behavior: session_pb2.SessionInitializationBehavior.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["file_path", b"file_path", "initialization_behavior", b"initialization_behavior"]) -> None: ...

global___InitializeFileRequest = InitializeFileRequest

@typing.final
class InitializeFileResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_NAME_FIELD_NUMBER: builtins.int
    NEW_SESSION_FIELD_NUMBER: builtins.int
    session_name: builtins.str
    new_session: builtins.bool
    def __init__(
        self,
        *,
        session_name: builtins.str = ...,
        new_session: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["new_session", b"new_session", "session_name", b"session_name"]) -> None: ...

global___InitializeFileResponse = InitializeFileResponse

@typing.final
class LogDataRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_NAME_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    session_name: builtins.str
    content: builtins.str
    def __init__(
        self,
        *,
        session_name: builtins.str = ...,
        content: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["content", b"content", "session_name", b"session_name"]) -> None: ...

global___LogDataRequest = LogDataRequest

@typing.final
class LogDataResponse(google.protobuf.message.Message):
    """Empty response message; success is indicated by the gRPC status code."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___LogDataResponse = LogDataResponse

@typing.final
class CloseFileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_NAME_FIELD_NUMBER: builtins.int
    session_name: builtins.str
    def __init__(
        self,
        *,
        session_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["session_name", b"session_name"]) -> None: ...

global___CloseFileRequest = CloseFileRequest

@typing.final
class CloseFileResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___CloseFileResponse = CloseFileResponse
