"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

This file is where the request and response messages for the
JsonLogger service are defined. It includes the service definition, request and response
messages, and enumerations for session initialization behavior.

The JsonLogger service provides methods to open a file for logging, log measurement
data, and close the file handle of a session.

The user can create a similar file for their services by following the structure of this file.
It is recommended to have Initialize or similar rpc call 
establishing or creating or opening the connection objects and 
Close or similar rpc calls for closing or destroying the connection objects.

We use InitializeFile and CloseFile as examples here.
It is highly recommended to use the same Session Initialization Behavior ENUM.
This ensures that the sessions are shareable across different measurement plugins.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _SessionInitializationBehavior:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SessionInitializationBehaviorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SessionInitializationBehavior.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SESSION_INITIALIZATION_BEHAVIOR_UNSPECIFIED: _SessionInitializationBehavior.ValueType  # 0
    """Automatically decide whether to initialize new or attach."""
    SESSION_INITIALIZATION_BEHAVIOR_INITIALIZE_NEW: _SessionInitializationBehavior.ValueType  # 1
    SESSION_INITIALIZATION_BEHAVIOR_ATTACH_TO_EXISTING: _SessionInitializationBehavior.ValueType  # 2

class SessionInitializationBehavior(_SessionInitializationBehavior, metaclass=_SessionInitializationBehaviorEnumTypeWrapper): ...

SESSION_INITIALIZATION_BEHAVIOR_UNSPECIFIED: SessionInitializationBehavior.ValueType  # 0
"""Automatically decide whether to initialize new or attach."""
SESSION_INITIALIZATION_BEHAVIOR_INITIALIZE_NEW: SessionInitializationBehavior.ValueType  # 1
SESSION_INITIALIZATION_BEHAVIOR_ATTACH_TO_EXISTING: SessionInitializationBehavior.ValueType  # 2
global___SessionInitializationBehavior = SessionInitializationBehavior

@typing.final
class InitializeFileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FILE_PATH_FIELD_NUMBER: builtins.int
    INITIALIZATION_BEHAVIOR_FIELD_NUMBER: builtins.int
    file_path: builtins.str
    """The complete file path."""
    initialization_behavior: global___SessionInitializationBehavior.ValueType
    """Defines how the session should be initialized."""
    def __init__(
        self,
        *,
        file_path: builtins.str = ...,
        initialization_behavior: global___SessionInitializationBehavior.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["file_path", b"file_path", "initialization_behavior", b"initialization_behavior"]) -> None: ...

global___InitializeFileRequest = InitializeFileRequest

@typing.final
class InitializeFileResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_NAME_FIELD_NUMBER: builtins.int
    NEW_SESSION_FIELD_NUMBER: builtins.int
    session_name: builtins.str
    new_session: builtins.bool
    def __init__(
        self,
        *,
        session_name: builtins.str = ...,
        new_session: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["new_session", b"new_session", "session_name", b"session_name"]) -> None: ...

global___InitializeFileResponse = InitializeFileResponse

@typing.final
class LogMeasurementDataRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MeasurementConfigurationsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    @typing.final
    class MeasurementOutputsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    SESSION_NAME_FIELD_NUMBER: builtins.int
    MEASUREMENT_NAME_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    MEASUREMENT_CONFIGURATIONS_FIELD_NUMBER: builtins.int
    MEASUREMENT_OUTPUTS_FIELD_NUMBER: builtins.int
    session_name: builtins.str
    measurement_name: builtins.str
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def measurement_configurations(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def measurement_outputs(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        session_name: builtins.str = ...,
        measurement_name: builtins.str = ...,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        measurement_configurations: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        measurement_outputs: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["measurement_configurations", b"measurement_configurations", "measurement_name", b"measurement_name", "measurement_outputs", b"measurement_outputs", "session_name", b"session_name", "timestamp", b"timestamp"]) -> None: ...

global___LogMeasurementDataRequest = LogMeasurementDataRequest

@typing.final
class LogMeasurementDataResponse(google.protobuf.message.Message):
    """Empty response message; success is indicated by the gRPC status code."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___LogMeasurementDataResponse = LogMeasurementDataResponse

@typing.final
class CloseFileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_NAME_FIELD_NUMBER: builtins.int
    session_name: builtins.str
    def __init__(
        self,
        *,
        session_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["session_name", b"session_name"]) -> None: ...

global___CloseFileRequest = CloseFileRequest

@typing.final
class CloseFileResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___CloseFileResponse = CloseFileResponse
