"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import client_session.stubs.json_logger_pb2 as json_logger_pb2
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class JsonLoggerStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    InitializeFile: grpc.UnaryUnaryMultiCallable[
        json_logger_pb2.InitializeFileRequest,
        json_logger_pb2.InitializeFileResponse,
    ]
    """Initializes the given JSON file for logging.
    Status Codes for errors:
    - INVALID_ARGUMENT: Invalid JSON File or Invalid Session Initialization Behavior.
    - PERMISSION_DENIED: Permission denied for the File.
    - INTERNAL: File path is invalid or inaccessible or any other unexpected behavior.
    - ALREADY_EXISTS: File has already been initialized and cannot be initialized again for SESSION_INITIALIZATION_BEHAVIOR_INITIALIZE_NEW.
    - NOT_FOUND: Session does not exist for SESSION_INITIALIZATION_BEHAVIOR_ATTACH_TO_EXISTING.
    """

    LogMeasurementData: grpc.UnaryUnaryMultiCallable[
        json_logger_pb2.LogMeasurementDataRequest,
        json_logger_pb2.LogMeasurementDataResponse,
    ]
    """Logs measurement data to the file of the session.
    Status Codes for errors:
    - PERMISSION_DENIED: Permission denied for the File.
    - NOT_FOUND: Session does not exist.
    - INTERNAL: File path is invalid or inaccessible or any other unexpected behavior.
    """

    CloseFile: grpc.UnaryUnaryMultiCallable[
        json_logger_pb2.CloseFileRequest,
        json_logger_pb2.CloseFileResponse,
    ]
    """Closes the file handle of the session.
    Status Codes for errors:
    - NOT_FOUND: Session does not exist.
    - INTERNAL: Any unexpected behavior.
    """

class JsonLoggerAsyncStub:
    InitializeFile: grpc.aio.UnaryUnaryMultiCallable[
        json_logger_pb2.InitializeFileRequest,
        json_logger_pb2.InitializeFileResponse,
    ]
    """Initializes the given JSON file for logging.
    Status Codes for errors:
    - INVALID_ARGUMENT: Invalid JSON File or Invalid Session Initialization Behavior.
    - PERMISSION_DENIED: Permission denied for the File.
    - INTERNAL: File path is invalid or inaccessible or any other unexpected behavior.
    - ALREADY_EXISTS: File has already been initialized and cannot be initialized again for SESSION_INITIALIZATION_BEHAVIOR_INITIALIZE_NEW.
    - NOT_FOUND: Session does not exist for SESSION_INITIALIZATION_BEHAVIOR_ATTACH_TO_EXISTING.
    """

    LogMeasurementData: grpc.aio.UnaryUnaryMultiCallable[
        json_logger_pb2.LogMeasurementDataRequest,
        json_logger_pb2.LogMeasurementDataResponse,
    ]
    """Logs measurement data to the file of the session.
    Status Codes for errors:
    - PERMISSION_DENIED: Permission denied for the File.
    - NOT_FOUND: Session does not exist.
    - INTERNAL: File path is invalid or inaccessible or any other unexpected behavior.
    """

    CloseFile: grpc.aio.UnaryUnaryMultiCallable[
        json_logger_pb2.CloseFileRequest,
        json_logger_pb2.CloseFileResponse,
    ]
    """Closes the file handle of the session.
    Status Codes for errors:
    - NOT_FOUND: Session does not exist.
    - INTERNAL: Any unexpected behavior.
    """

class JsonLoggerServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def InitializeFile(
        self,
        request: json_logger_pb2.InitializeFileRequest,
        context: _ServicerContext,
    ) -> typing.Union[json_logger_pb2.InitializeFileResponse, collections.abc.Awaitable[json_logger_pb2.InitializeFileResponse]]:
        """Initializes the given JSON file for logging.
        Status Codes for errors:
        - INVALID_ARGUMENT: Invalid JSON File or Invalid Session Initialization Behavior.
        - PERMISSION_DENIED: Permission denied for the File.
        - INTERNAL: File path is invalid or inaccessible or any other unexpected behavior.
        - ALREADY_EXISTS: File has already been initialized and cannot be initialized again for SESSION_INITIALIZATION_BEHAVIOR_INITIALIZE_NEW.
        - NOT_FOUND: Session does not exist for SESSION_INITIALIZATION_BEHAVIOR_ATTACH_TO_EXISTING.
        """

    @abc.abstractmethod
    def LogMeasurementData(
        self,
        request: json_logger_pb2.LogMeasurementDataRequest,
        context: _ServicerContext,
    ) -> typing.Union[json_logger_pb2.LogMeasurementDataResponse, collections.abc.Awaitable[json_logger_pb2.LogMeasurementDataResponse]]:
        """Logs measurement data to the file of the session.
        Status Codes for errors:
        - PERMISSION_DENIED: Permission denied for the File.
        - NOT_FOUND: Session does not exist.
        - INTERNAL: File path is invalid or inaccessible or any other unexpected behavior.
        """

    @abc.abstractmethod
    def CloseFile(
        self,
        request: json_logger_pb2.CloseFileRequest,
        context: _ServicerContext,
    ) -> typing.Union[json_logger_pb2.CloseFileResponse, collections.abc.Awaitable[json_logger_pb2.CloseFileResponse]]:
        """Closes the file handle of the session.
        Status Codes for errors:
        - NOT_FOUND: Session does not exist.
        - INTERNAL: Any unexpected behavior.
        """

def add_JsonLoggerServicer_to_server(servicer: JsonLoggerServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
