"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Protocol:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ProtocolEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Protocol.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SPI: _Protocol.ValueType  # 0
    I2C: _Protocol.ValueType  # 1
    UART: _Protocol.ValueType  # 2

class Protocol(_Protocol, metaclass=_ProtocolEnumTypeWrapper):
    """Protocol enumeration for device communication"""

SPI: Protocol.ValueType  # 0
I2C: Protocol.ValueType  # 1
UART: Protocol.ValueType  # 2
global___Protocol = Protocol

class _SessionInitializationBehavior:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SessionInitializationBehaviorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SessionInitializationBehavior.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SESSION_INITIALIZATION_BEHAVIOR_UNSPECIFIED: _SessionInitializationBehavior.ValueType  # 0
    """Automatically decide whether to initialize new or attach."""
    SESSION_INITIALIZATION_BEHAVIOR_INITIALIZE_NEW: _SessionInitializationBehavior.ValueType  # 1
    SESSION_INITIALIZATION_BEHAVIOR_ATTACH_TO_EXISTING: _SessionInitializationBehavior.ValueType  # 2

class SessionInitializationBehavior(_SessionInitializationBehavior, metaclass=_SessionInitializationBehaviorEnumTypeWrapper): ...

SESSION_INITIALIZATION_BEHAVIOR_UNSPECIFIED: SessionInitializationBehavior.ValueType  # 0
"""Automatically decide whether to initialize new or attach."""
SESSION_INITIALIZATION_BEHAVIOR_INITIALIZE_NEW: SessionInitializationBehavior.ValueType  # 1
SESSION_INITIALIZATION_BEHAVIOR_ATTACH_TO_EXISTING: SessionInitializationBehavior.ValueType  # 2
global___SessionInitializationBehavior = SessionInitializationBehavior

@typing.final
class InitializeRequest(google.protobuf.message.Message):
    """Request/Response messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEVICE_ID_FIELD_NUMBER: builtins.int
    PROTOCOL_FIELD_NUMBER: builtins.int
    RESET_FIELD_NUMBER: builtins.int
    REGISTER_MAP_FIELD_NUMBER: builtins.int
    INITIALIZATION_BEHAVIOR_FIELD_NUMBER: builtins.int
    device_id: builtins.str
    protocol: global___Protocol.ValueType
    reset: builtins.bool
    register_map: builtins.str
    initialization_behavior: global___SessionInitializationBehavior.ValueType
    def __init__(
        self,
        *,
        device_id: builtins.str = ...,
        protocol: global___Protocol.ValueType = ...,
        reset: builtins.bool = ...,
        register_map: builtins.str = ...,
        initialization_behavior: global___SessionInitializationBehavior.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["device_id", b"device_id", "initialization_behavior", b"initialization_behavior", "protocol", b"protocol", "register_map", b"register_map", "reset", b"reset"]) -> None: ...

global___InitializeRequest = InitializeRequest

@typing.final
class WriteRegisterRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    name: builtins.str
    value: builtins.int
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        value: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "value", b"value"]) -> None: ...

global___WriteRegisterRequest = WriteRegisterRequest

@typing.final
class ReadRegisterRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___ReadRegisterRequest = ReadRegisterRequest

@typing.final
class ReadRegisterResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    value: builtins.int
    def __init__(
        self,
        *,
        value: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["value", b"value"]) -> None: ...

global___ReadRegisterResponse = ReadRegisterResponse

@typing.final
class WriteGpioChannelRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PORT_FIELD_NUMBER: builtins.int
    CHANNEL_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    port: builtins.int
    channel: builtins.int
    state: builtins.bool
    def __init__(
        self,
        *,
        port: builtins.int = ...,
        channel: builtins.int = ...,
        state: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["channel", b"channel", "port", b"port", "state", b"state"]) -> None: ...

global___WriteGpioChannelRequest = WriteGpioChannelRequest

@typing.final
class ReadGpioChannelRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PORT_FIELD_NUMBER: builtins.int
    CHANNEL_FIELD_NUMBER: builtins.int
    port: builtins.int
    channel: builtins.int
    def __init__(
        self,
        *,
        port: builtins.int = ...,
        channel: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["channel", b"channel", "port", b"port"]) -> None: ...

global___ReadGpioChannelRequest = ReadGpioChannelRequest

@typing.final
class ReadGpioChannelResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATE_FIELD_NUMBER: builtins.int
    state: builtins.bool
    def __init__(
        self,
        *,
        state: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["state", b"state"]) -> None: ...

global___ReadGpioChannelResponse = ReadGpioChannelResponse

@typing.final
class WriteGpioPortRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PORT_FIELD_NUMBER: builtins.int
    MASK_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    port: builtins.int
    mask: builtins.int
    state: builtins.int
    def __init__(
        self,
        *,
        port: builtins.int = ...,
        mask: builtins.int = ...,
        state: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["mask", b"mask", "port", b"port", "state", b"state"]) -> None: ...

global___WriteGpioPortRequest = WriteGpioPortRequest

@typing.final
class ReadGpioPortRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PORT_FIELD_NUMBER: builtins.int
    MASK_FIELD_NUMBER: builtins.int
    port: builtins.int
    mask: builtins.int
    def __init__(
        self,
        *,
        port: builtins.int = ...,
        mask: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["mask", b"mask", "port", b"port"]) -> None: ...

global___ReadGpioPortRequest = ReadGpioPortRequest

@typing.final
class ReadGpioPortResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATE_FIELD_NUMBER: builtins.int
    state: builtins.int
    def __init__(
        self,
        *,
        state: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["state", b"state"]) -> None: ...

global___ReadGpioPortResponse = ReadGpioPortResponse

@typing.final
class StatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    status: builtins.str
    error_message: builtins.str
    def __init__(
        self,
        *,
        status: builtins.str = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_message", b"error_message", "status", b"status"]) -> None: ...

global___StatusResponse = StatusResponse

@typing.final
class CloseRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___CloseRequest = CloseRequest
